### ISSUE TITLE
The server does not start due to an error : "Error: error:0909006C:PEM routines:get_name:no start line"

### ISSUE THREAD

**Issue by ravayak** [TensorTom/superPeer#2]
# Error on windows 10, node v13.0.1 : 

> npm run server

> superpeer@0.6.0 server D:\projects\gun\TensorTom\superPeer
> node index.js

Hello wonderful person! :) Thanks for using GUN, feel free to ask for help on https://gitter.im/amark/gun and ask StackOverflow questions tagged with 'gun'!
_tls_common.js:131
      c.context.setCert(cert);
                ^

Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:131:17)
    at Server.setSecureContext (_tls_wrap.js:1155:27)
    at Server (_tls_wrap.js:1033:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:85:10)
    at Object.<anonymous> (D:\projects\gun\TensorTom\superPeer\index.js:53:23)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superpeer@0.6.0 server: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superpeer@0.6.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\antonny\AppData\Roaming\npm-cache\_logs\2020-04-13T15_38_14_503Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superpeer@0.6.0 start: `npm run server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superpeer@0.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\antonny\AppData\Roaming\npm-cache\_logs\2020-04-13T15_38_14_535Z-debug.log

**Comment by bitnom** [comment]
This means that you are not loading a valid SSL certificate. Either copy a valid certificate to the `/cert` directory (I typically use Let'sEncrypt to generate) or disable SSL in superPeer by setting `useSSL = false` in https://github.com/TensorTom/superPeer/blob/master/index.js
